#!/bin/bash
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#

# If you want to use GNOME config tools...
#
#if test -x /usr/lib/openbox/gnome-settings-daemon >/dev/null; then
#  /usr/lib/openbox/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null 2>&1; then
#  gnome-settings-daemon &
#fi

# If you want to use XFCE config tools...
#
#xfce-mcs-manager &
legion-kb-rgb load-profile --path /home/narmis/Documents/dim-white.json &
xwallpaper --stretch $(find ~/Pictures/wallpapers -type f | shuf -n1) &
picom --config ~/.config/picom/picom.conf --animations --experimental-backends &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
~/.local/bin/battery.sh &
~/.local/bin/ncmpcpp_notify.sh &
/usr/bin/mpd-discord-rpc &
